package br.com.mackenzie.peladafc.view;

import br.com.mackenzie.peladafc.controller.JogadorController;
import br.com.mackenzie.peladafc.controller.ModalidadeController;
import br.com.mackenzie.peladafc.controller.PartidaController;
import br.com.mackenzie.peladafc.controller.TimeController;
import br.com.mackenzie.peladafc.model.Modalidade;
import br.com.mackenzie.peladafc.model.Time;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : PeladaFC
//  @ File Name : PeladaView.java
//  @ Date : 07/09/2013
//  @ Author : 
//
//




/** */
public class PeladaView {
	/** */
	public ModalidadeController modalidadeController;
	
	/** */
	public JogadorController jogadorController;
	
	/** */
	public TimeController timeController;
	
	/** */
	public PartidaController partidaController;
	
	/** */
	protected Modalidade escolherModalidade() {
		return null;
	
	}
	
	/** */
	protected void iniciarPelada(Modalidade modalidade) {
	
	}
	
	/** */
	protected void onTouchCadastrarJogador() {
	
	}
	
	/** */
	protected void onTouchDefinirJogadoresPelada() {
	
	}
	
	/** */
	protected void onTouchSortearTimes() {
	
	}
	
	/** */
	protected void onTouchIniciarPartida() {
	
	}
	
	/** */
	protected void iniciarWebSite() {
	
	}
	
	/** */
	protected void iniciarPartida(Time timeA, Time timeB) {
	
	}
	
	/** */
	protected void finalizarPelada() {
	
	}
	
	/** */
	protected void outraPartida() {
	
	}
}
