package br.com.mackenzie.peladafc.controller;

import java.util.ArrayList;
import java.util.List;

import android.content.Context;
import br.com.mackenzie.peladafc.dao.JogadorDAO;
import br.com.mackenzie.peladafc.model.Jogador;
import br.com.mackenzie.peladafc.exception.*;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : PeladaFC
//  @ File Name : JogadorController.java
//  @ Date : 07/09/2013
//  @ Author : 
//
//


/** */
public class JogadorController {
	/** */
	private List<Jogador> jogadores;
	
	/** */
	private Jogador jogador;
		
	/** */
	private JogadorDAO jogadorDAO;
	
	/**
	 * @throws DAOException  */
	public void adicionar(String nome, String apelido) throws DAOException {
		jogador = new Jogador(nome,apelido,3);
		jogadorDAO.adiciona(jogador);
	}
	
	/**
	 * @throws DAOException 
	 * @throws ConsultarJogadorException  */
	public List<Jogador> consultarPorNome(String nome) throws ControllerException, DAOException {
		if(nome.length() > 2)
			jogadores = jogadorDAO.obterListaJogadorNome(nome);
		else
			throw new ControllerException("Para iniciar a consulta é preciso ter no mínimo 3 caracteres na palavra");
			
		return jogadores;
	}
	
	/**
	 * @throws DAOException  */
	public void atualizar(Jogador jogador) throws DAOException {
		jogadorDAO.atualiza(jogador);
	}
	
	/**
	 * @throws DAOException 
	 * @throws ConsultarJogadorException  */
	public List<Jogador> obterJogadoresApelido(String apelido) throws ControllerException, DAOException {
		if(apelido.length() > 2)
			jogadores = jogadorDAO.obterListaJogadorApelido(apelido);
		else
			throw new ControllerException("Para iniciar a consulta é preciso ter no mínimo 3 caracteres na palavra");
			
		return jogadores;
	}
	
	/**
	 * @throws DAOException  */
	public List<Jogador> obterJogadores() throws DAOException {
		return jogadorDAO.obterListaJogadores();
	}

	/** */
	public JogadorController(Context context) {
		this.jogadores =  new ArrayList<Jogador>();
		this.jogadorDAO = new JogadorDAO(context);
	}
	
	
}
