package br.com.mackenzie.peladafc.controller;

import java.util.LinkedList;
import java.util.List;

import br.com.mackenzie.peladafc.dao.JogadorDAO;
import br.com.mackenzie.peladafc.model.Jogador;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : PeladaFC
//  @ File Name : JogadorController.java
//  @ Date : 07/09/2013
//  @ Author : 
//
//




/** */
public class JogadorController {
	/** */
	private LinkedList<Jogador> jogadores;
	
	/** */
	private JogadorController instance;
	
	/** */
	public Jogador jogador;
		
	/** */
	public JogadorDAO jogadorDAO;
	
	/** */
	public void adicionar(String nome, String apelido) {
	
	}
	
	/** */
	public Jogador consultarPorNome(Object nome) {
		return null;
	
	}
	
	/** */
	public void atualizar(Object jogador) {
	
	}
	
	/** */
	public Jogador obterJogadorApelido(String apelido) {
		return null;
	
	}
	
	/** */
	public List<Jogador> obterJogadores() {
		return null;
		
	}
	
	/** */
	public JogadorController getInstance() {
		return null;
		
	}
	
	/** */
	private JogadorController() {
		
	}
}
