package br.com.mackenzie.peladafc.controller;

import java.util.List;

import br.com.mackenzie.peladafc.dao.ModalidadeDAO;
import br.com.mackenzie.peladafc.model.Modalidade;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : PeladaFC
//  @ File Name : ModalidadeController.java
//  @ Date : 07/09/2013
//  @ Author : 
//
//




/** */
public class ModalidadeController {
	/** */
	public Modalidade modalidade;
	
	/** */
	public ModalidadeDAO modalidadeDAO;
	
	/** */
	public Modalidade escolherModalidade() {
		return null;
	}
	
	/** */
	public List<Modalidade> obterModalidades() {
		return null;
	}
	
	/** */
	public Modalidade obterModalidade() {
		return null;
	}
}
