package br.com.mackenzie.peladafc.controller;

import java.util.List;

import android.content.Context;
import br.com.mackenzie.peladafc.dao.ModalidadeDAO;
import br.com.mackenzie.peladafc.exception.DAOException;
import br.com.mackenzie.peladafc.model.Modalidade;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : PeladaFC
//  @ File Name : ModalidadeController.java
//  @ Date : 07/09/2013
//  @ Author : 
//
//




/** */
public class ModalidadeController {
	/** */
	public Modalidade modalidade;
	
	/** */
	public ModalidadeDAO modalidadeDAO;
	
	/** */
	public Modalidade escolherModalidade() {
		return modalidade;
	}
	
	/**
	 * @throws DAOException  */
	public List<Modalidade> obterModalidades() throws DAOException {
		return this.modalidadeDAO.obterModalidades();
	}
	
	/** */
	public Modalidade obterModalidade() {
		return null;
	}
	
	public ModalidadeController(Context context) {
		// TODO Auto-generated constructor stub
		this.modalidadeDAO = new ModalidadeDAO(context);
		this.modalidade = new Modalidade();
	}
}
