package br.com.mackenzie.peladafc.controller;

import java.util.List;

import br.com.mackenzie.peladafc.model.Partida;
import br.com.mackenzie.peladafc.model.Time;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : PeladaFC
//  @ File Name : PartidaController.java
//  @ Date : 07/09/2013
//  @ Author : 
//
//




/** */
public class PartidaController {
	/** */
	private PartidaController instance;
	
	/** */
	public Partida Unnamed1;
	
	/** */
	public void iniciarPartida(Time timeA, Time timeB) {
	
	}
	
	/** */
	public List<Time> finalizarPartida() {
		return null;
	
	}
	
	/** */
	public PartidaController getInstance() {
		return instance;
	
	}
	
	/** */
	private PartidaController() {
	
	}
}
