package br.com.mackenzie.peladafc.controller;

import java.util.List;

import br.com.mackenzie.peladafc.dao.TimeDAO;
import br.com.mackenzie.peladafc.model.Jogador;
import br.com.mackenzie.peladafc.model.Time;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : PeladaFC
//  @ File Name : SorteioStrategy.java
//  @ Date : 07/09/2013
//  @ Author : 
//
//




/** */
public class SorteioStrategy {
	/** */
	public TimeDAO timeDAO;
	
	/** */
	public List<Time> sortear(List<Jogador> jogadores, int qtdJogadoresPortime) {
		return null;
	}
}
