package br.com.mackenzie.peladafc.controller;



import java.util.List;

import br.com.mackenzie.peladafc.dao.TimeDAO;
import br.com.mackenzie.peladafc.model.Jogador;
import br.com.mackenzie.peladafc.model.Time;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : PeladaFC
//  @ File Name : TimeController.java
//  @ Date : 07/09/2013
//  @ Author : 
//
//




/** */
public class TimeController {
	/** */
	private List<Time> times;
	
	/** */
	public SorteioStrategy sorteioStrategy;
	
	/** */
	public JogadorController jogadorController;
	
	/** */
	public Time time;
	
	/** */
	public ModalidadeController modalidadeController;
	
	/** */
	public TimeDAO timeDAO ;
	
	/** */
	public void sortear(List<Jogador>jogadores, int qtdJogadoresPorTime) {
	
	}
	
	/** */
	public Time obterTimePorId(int id) {
		return null;
	}
}
