package br.com.mackenzie.peladafc.model;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : PeladaFC
//  @ File Name : Jogador.java
//  @ Date : 07/09/2013
//  @ Author : 
//
//




/** */
public class Jogador {
	/** */
	private int id;
	
	/** */
	private String nome;
	
	/** */
	private String apelido;
	
	/** */
	private int classificao;
	
}
