package br.com.mackenzie.peladafc.model;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : PeladaFC
//  @ File Name : Modalidade.java
//  @ Date : 07/09/2013
//  @ Author : 
//
//




/** */
public class Modalidade {
	/** */
	private int id;
	
	/** */
	private String descricao;
	
	/** */
	private int jogadoresPorTime;

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDescricao() {
		return descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	public int getJogadoresPorTime() {
		return jogadoresPorTime;
	}

	public void setJogadoresPorTime(int jogadoresPorTime) {
		this.jogadoresPorTime = jogadoresPorTime;
	}
}
