package br.com.mackenzie.peladafc.model;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : PeladaFC
//  @ File Name : Modalidade.java
//  @ Date : 07/09/2013
//  @ Author : 
//
//




/** */
public class Modalidade {
	/** */
	private int id;
	
	/** */
	private String descricao;
	
	/** */
	private int jogadoresPorTime;
}
