package br.com.mackenzie.peladafc.model;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : PeladaFC
//  @ File Name : Partida.java
//  @ Date : 07/09/2013
//  @ Author : 
//
//




/** */
public class Partida {
	/** */
	public Time timeA;
	
	/** */
	public Time timeB;
	

}
