package br.com.mackenzie.peladafc.model;

import java.util.List;

import br.com.mackenzie.peladafc.controller.TimeController;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : PeladaFC
//  @ File Name : Time.java
//  @ Date : 07/09/2013
//  @ Author : 
//
//




/** */
public class Time {
	/** */
	private Object id;
	
	/** */
	private Object nome;
	
	/** */
	private List<Jogador> escalacao;
	
	/** */
	public Partida Unnamed1;
	
	/** */
	public Jogador Unnamed2;
	
	/** */
	public TimeController Unnamed3;
}
