package br.com.mackenzie.peladafc.dao;

import java.util.List;

import br.com.mackenzie.peladafc.model.Jogador;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : PeladaFC
//  @ File Name : JogadorDAO.java
//  @ Date : 07/09/2013
//  @ Author : 
//
//




/** */
public class JogadorDAO {

	
	/** */
	public JogadorDAO instance;
	
	/** */
	public void adiciona(Jogador jogador) {
	
	}
	
	/** */
	public void atualiza(Jogador jogador) {
	
	}
	
	/** */
	public List<Jogador> obterListaJogadores() {
		return null;
	
	}
	
	/** */
	public Jogador obterJogador(int id) {
		return null;
	}
	
	/** */
	public List<Jogador> obterListaJogadorApelido(String apelido) {
		return null;
	}
	
	/** */
	public List<Jogador> obterListaJogadorNome(String nome) {
		return null;
	}
	
	/** */
	public JogadorDAO getInstance() {
		return null;
	}
}
