package br.com.mackenzie.peladafc.dao;

import java.util.List;

import br.com.mackenzie.peladafc.controller.JogadorController;
import br.com.mackenzie.peladafc.model.Modalidade;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : PeladaFC
//  @ File Name : ModalidadeDAO.java
//  @ Date : 07/09/2013
//  @ Author : 
//
//




/** */
public class ModalidadeDAO {
	
	/** */
	public ModalidadeDAO instance;
	
	/** */
	public List<Modalidade> obterModalidades() {
		return null;
	}
	
	/** */
	public Modalidade obterModalidade(int id) {
		return null;
	}
	
	/** */
	public JogadorController getInstance() {
		return null;
	}
}
