package br.com.mackenzie.peladafc.dao;

import java.util.List;

import br.com.mackenzie.peladafc.model.Time;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : PeladaFC
//  @ File Name : TimeDAO.java
//  @ Date : 07/09/2013
//  @ Author : 
//
//




/** */
public class TimeDAO {
	
	/** */
	public TimeDAO instance;
	
	/** */
	public void inserirTime(Time time) {
	
	}
	
	/** */
	public void excluirTimes() {
	
	}
	
	/** */
	public Time obterTime(int id) {
		return null;
	}
	
	/** */
	public List<Time> obterTimes() {
		return null;
	}
	
	/** */
	public TimeDAO getInstance() {
		return null;
	}
}
